@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3JvbiIsImNyZWF0aW9uRGF0ZSI6IjIwMjItMDQtMjEiLCJpYXQiOjE2NTA1NjYxOTIsImV4cCI6MTY1MDY1MjU5Mn0.lZOHKhU1S3Dwwshxk33cMPUAPJUdMhbZRpE4t0qzUBQ

### Affiche le contact {id}
GET http://localhost:3000/contact/9 HTTP/1.1
Authorization: Bearer {{token}}

### Affiche tous les contacts
GET http://localhost:3000/getContact HTTP/1.1
Authorization: Bearer {{token}}

### Supprime le contact {id}
DELETE http://localhost:3000/deleteContact/1 HTTP/1.1
Authorization: Bearer {{token}}

### Ajoute le contact
POST http://localhost:3000/addContact/liste/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "George",
    "firstname": "Paul",
    "mail": "p.george@gmail.com"
}

### Modifie le nom de contact
PUT http://localhost:3000/updateContact/Zinedine/Yvan HTTP/1.1
