@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3JvbiIsImNyZWF0aW9uRGF0ZSI6IjIwMjItMDQtMjEiLCJpYXQiOjE2NTA1NjYxOTIsImV4cCI6MTY1MDY1MjU5Mn0.lZOHKhU1S3Dwwshxk33cMPUAPJUdMhbZRpE4t0qzUBQ

### Affiche la liste {1}
GET http://localhost:3000/contactList/1 HTTP/1.1

### Affiche toutes les listes
GET http://localhost:3000/getList HTTP/1.1

### Supprime la liste {id}
DELETE http://localhost:3000/deleteList/3 HTTP/1.1

### Ajout d'une liste
POST  http://localhost:3000/addList HTTP/1.1
content-type: application/json

{
    "name": "Travail",
    "description": "Liste de travail"
}

### Modification du nom de la liste
PUT http://localhost:3000/updateList/Travail/Boulot HTTP/1.1
