@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3JvbiIsImNyZWF0aW9uRGF0ZSI6IjIwMjItMDQtMjEiLCJpYXQiOjE2NTA5NjY2NjUsImV4cCI6MTY1MTA1MzA2NX0.3LlJMM2_y7fI9bFQ4SacUl6CfWv9k_tyo0jzUDqoHKU

### Affiche le contact {id}
GET http://localhost:3000/contact/1 HTTP/1.1
Authorization: Bearer {{token}}

### Affiche tous les contacts
GET http://localhost:3000/getContact HTTP/1.1
Authorization: Bearer {{token}}

### Supprime le contact {id}
DELETE http://localhost:3000/deleteContact/1 HTTP/1.1
Authorization: Bearer {{token}}

### Ajoute le contact
POST http://localhost:3000/addContact/liste/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Chris",
    "firstname": "Paul",
    "mail": "c.george@gmail.com"
}

### Modifie le nom de contact
PUT http://localhost:3000/updateContact/Zinedine/Yvan HTTP/1.1
Authorization: Bearer {{token}}
