### Affiche tous les messages
GET http://localhost:3000/message HTTP/1.1

### Affiche le messsage {id}
GET http://localhost:3000/message/1 HTTP/1.1

### Supprime le message {id}
DELETE http://localhost:3000/message/1 HTTP/1.1

### Ajout d'un message
POST http://localhost:3000/addMessage HTTP/1.1
content-type: application/json

{
    "object": "Facture ",
    "content": "Voici votre facture de test",
    "senddate": "2022-04-20",
    "sentdate": "2022-04-25",
    "sendhour": "10:00",
    "senthour": "10:30",
    "idstate": 3,
    "idlist": 1,
    "idmodel": 3
}
### Modifie un message

