@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3JvbiIsImNyZWF0aW9uRGF0ZSI6IjIwMjItMDQtMjEiLCJpYXQiOjE2NTA1NjYxOTIsImV4cCI6MTY1MDY1MjU5Mn0.lZOHKhU1S3Dwwshxk33cMPUAPJUdMhbZRpE4t0qzUBQ

###Ajout/Création d'un état de message
POST http://localhost:3000/state/attente HTTP/1.1
Authorization: Bearer {{token}}

### Suppression d'un etat
DELETE http://localhost:3000/state/9 HTTP/1.1
Authorization: Bearer {{token}}

###Liste des états
GET http://localhost:3000/state HTTP/1.1
Authorization: Bearer {{token}}

###Label de l'etat en fonction de son id
GET http://localhost:3000/state/10 HTTP/1.1
Authorization: Bearer {{token}}

###Met a jour un etat
PUT  http://localhost:3000/state/299?label=pret HTTP/1.1
Authorization: Bearer {{token}}
