@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3JvbiIsImNyZWF0aW9uRGF0ZSI6IjIwMjItMDQtMjEiLCJpYXQiOjE2NTA1NjYxOTIsImV4cCI6MTY1MDY1MjU5Mn0.lZOHKhU1S3Dwwshxk33cMPUAPJUdMhbZRpE4t0qzUBQ

###Total de contact
GET  http://localhost:3000/nbContact HTTP/1.1

###Total de liste
GET  http://localhost:3000/totalListe HTTP/1.1
###Total de message envoyés
GET  http://localhost:3000/nbMessageEnvoye HTTP/1.1

###Dernier message envoyé
GET  http://localhost:3000/derniermessage HTTP/1.1

###Nombre de message par type
GET  http://localhost:3000/nbMsgType HTTP/1.1
